### ISSUE TITLE
Upgrade mongoose-schema-jsonschema to 2.0.0

### ISSUE THREAD

**Issue by TheRav3n** [lykmapipo/mongoose-common#16]
Please upgrade mongoose-schema-jsonschema to 2.0.0 in package.json in order to support mongoose 6.0.2.

Opened PR #17

**Comment by PierreBrisorgueil** [comment]
hello @lykmapipo +1 for this, it's also broke mongoose-gridfs with mongoose 6.x

**Comment by lykmapipo** [comment]
@TheRav3n & @PierreBrisorgueil On it

**Comment by PierreBrisorgueil** [comment]
Thx ! 🙏

**Comment by lykmapipo** [comment]
Fixed in v0.40.0

**Comment by PierreBrisorgueil** [comment]
Thx, always stuck on this one https://github.com/lykmapipo/mongoose-gridfs/issues/71 🤔
